"""changing courses structure table & creating modality table

Revision ID: 11913f53ecc7
Revises: 11007ba3a763
Create Date: 2025-11-18 16:26:05.143862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11913f53ecc7'
down_revision: Union[str, Sequence[str], None] = '11007ba3a763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalities',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalities_name'), 'modalities', ['name'], unique=True)
    op.add_column('courses', sa.Column('status', sa.Enum('active', 'inactive', name='status_enum'), nullable=False))
    op.add_column('courses', sa.Column('modality_id', sa.String(length=36), nullable=True))
    op.add_column('courses', sa.Column('num_hours', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('credits', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('price', sa.Float(), nullable=False))
    op.create_index(op.f('ix_courses_modality_id'), 'courses', ['modality_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'modalities', ['modality_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_modality_id'), table_name='courses')
    op.drop_column('courses', 'price')
    op.drop_column('courses', 'credits')
    op.drop_column('courses', 'num_hours')
    op.drop_column('courses', 'modality_id')
    op.drop_column('courses', 'status')
    op.drop_index(op.f('ix_modalities_name'), table_name='modalities')
    op.drop_table('modalities')
    # ### end Alembic commands ###
