"""new columns target, content & start_info to courses

Revision ID: 11e256bd99f1
Revises: 252cf7c1ea89
Create Date: 2025-12-09 11:19:10.226687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e256bd99f1'
down_revision: Union[str, Sequence[str], None] = '252cf7c1ea89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('target', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('start_info', sa.Text(), nullable=True))
    op.alter_column('courses', 'num_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('courses', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'num_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('courses', 'start_info')
    op.drop_column('courses', 'target')
    op.drop_column('courses', 'content')
    # ### end Alembic commands ###
