"""init all tables

Revision ID: 1aeed39d97a2
Revises: 
Create Date: 2025-11-10 16:08:55.769116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aeed39d97a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_course',
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id', 'course_id')
    )
    op.create_index(op.f('ix_area_course_area_id'), 'area_course', ['area_id'], unique=False)
    op.create_index(op.f('ix_area_course_course_id'), 'area_course', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_area_course_course_id'), table_name='area_course')
    op.drop_index(op.f('ix_area_course_area_id'), table_name='area_course')
    op.drop_table('area_course')
    # ### end Alembic commands ###
