"""adding photo column to course table

Revision ID: 252cf7c1ea89
Revises: 11913f53ecc7
Create Date: 2025-11-18 17:06:15.251676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252cf7c1ea89'
down_revision: Union[str, Sequence[str], None] = '11913f53ecc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'photo')
    # ### end Alembic commands ###
