"""new badges and award tables

Revision ID: 534360932ffa
Revises: abe4fd15e434
Create Date: 2026-01-05 00:41:55.469071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '534360932ffa'
down_revision: Union[str, Sequence[str], None] = 'abe4fd15e434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('quiz_badge_awards',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quiz_id', name='uq_badge_award_user_quiz')
    )
    op.create_index(op.f('ix_quiz_badge_awards_attempt_id'), 'quiz_badge_awards', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_badge_awards_badge_id'), 'quiz_badge_awards', ['badge_id'], unique=False)
    op.create_index(op.f('ix_quiz_badge_awards_quiz_id'), 'quiz_badge_awards', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_badge_awards_user_id'), 'quiz_badge_awards', ['user_id'], unique=False)
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender_enum'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_quiz_badge_awards_user_id'), table_name='quiz_badge_awards')
    op.drop_index(op.f('ix_quiz_badge_awards_quiz_id'), table_name='quiz_badge_awards')
    op.drop_index(op.f('ix_quiz_badge_awards_badge_id'), table_name='quiz_badge_awards')
    op.drop_index(op.f('ix_quiz_badge_awards_attempt_id'), table_name='quiz_badge_awards')
    op.drop_table('quiz_badge_awards')
    op.drop_table('badges')
    # ### end Alembic commands ###
