"""new gender and birthdate columns to user

Revision ID: 74d9ec3da8c4
Revises: 3cf48beaf56a
Create Date: 2026-01-05 01:41:13.579045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d9ec3da8c4'
down_revision: Union[str, Sequence[str], None] = '3cf48beaf56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
