"""creating videos table and adding to courses

Revision ID: 80c8a4be1664
Revises: 11e256bd99f1
Create Date: 2025-12-09 12:31:35.547932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c8a4be1664'
down_revision: Union[str, Sequence[str], None] = '11e256bd99f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('courses', sa.Column('video_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_courses_video_id'), 'courses', ['video_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'videos', ['video_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_video_id'), table_name='courses')
    op.drop_column('courses', 'video_id')
    op.drop_table('videos')
    # ### end Alembic commands ###
