"""new status enum column on quiz table

Revision ID: abe4fd15e434
Revises: cb1a9f325265
Create Date: 2026-01-03 18:06:20.370994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe4fd15e434'
down_revision: Union[str, Sequence[str], None] = 'cb1a9f325265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('status', sa.Enum('active', 'inactive', name='status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'status')
    # ### end Alembic commands ###
