"""adding video to quiz and deleting to course

Revision ID: c0c3c3475509
Revises: 80c8a4be1664
Create Date: 2025-12-09 12:36:09.875615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c3c3475509'
down_revision: Union[str, Sequence[str], None] = '80c8a4be1664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_video_id'), table_name='courses')
    op.drop_constraint(op.f('courses_video_id_fkey'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'video_id')
    op.add_column('quizzes', sa.Column('video_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_quizzes_video_id'), 'quizzes', ['video_id'], unique=False)
    op.create_foreign_key(None, 'quizzes', 'videos', ['video_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_index(op.f('ix_quizzes_video_id'), table_name='quizzes')
    op.drop_column('quizzes', 'video_id')
    op.add_column('courses', sa.Column('video_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('courses_video_id_fkey'), 'courses', 'videos', ['video_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_courses_video_id'), 'courses', ['video_id'], unique=False)
    # ### end Alembic commands ###
